version: '3'
services:
  app:
    container_name: docker-easypol
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: docker-mongo-easypol
    image: mongo:5
    ports:
      - '27017:27017'